# Auto assign reviewers configuration

# Set to true to add reviewers to pull requests
addReviewers: true

# Set to true to add assignees to pull requests
addAssignees: false

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - # Add your team members' GitHub usernames here

# A number of reviewers added to the pull request
numberOfReviewers: 2

# A list of assignees, overrides reviewers if set
assignees:
  - # Add assignees if needed

# A number of assignees to add to the pull request
numberOfAssignees: 0

# A list of keywords to be skipped the process if PR's title include it
skipKeywords:
  - wip
  - WIP
  - draft
