name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Validate PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |
          feat
          fix
          docs
          style
          refactor
          perf
          test
          build
          ci
          chore
          revert
    
    - name: Check for merge conflicts
      run: |
        git fetch origin ${{ github.base_ref }}
        git merge-tree $(git merge-base HEAD origin/${{ github.base_ref }}) HEAD origin/${{ github.base_ref }} | grep -q '<<<<<' && exit 1 || exit 0
    
    - name: Conventional commits check
      uses: wagoid/commitlint-github-action@v6

  size-label:
    name: PR Size Labeling
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
    - name: Label PR based on size
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        xs_max_size: 10
        s_label: 'size/s'
        s_max_size: 100
        m_label: 'size/m'
        m_max_size: 500
        l_label: 'size/l'
        l_max_size: 1000
        xl_label: 'size/xl'
        fail_if_xl: false

  auto-assign:
    name: Auto Assign Reviewers
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    
    steps:
    - name: Auto assign PR
      uses: kentaro-m/auto-assign-action@v2.0.0
      with:
        configuration-path: '.github/auto-assign.yml'
